imports:
    - { resource: config_dev.yml }

framework:
    test: ~
    session:
        storage_id: session.storage.filesystem

web_profiler:
    toolbar: false
    intercept_redirects: false

swiftmailer:
    disable_delivery: true


mink:
    base_url:   http://localhost:10085/app_test.php
    
behat:
  context:
    class: LoginFeatureContext