<?php

namespace Guepe\CrmBankBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * TestAccountRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestAccountRepository extends EntityRepository
{
}