parameters:
#    guepe_user.example.class: Guepe\UserBundle\Example

services:
#    guepe_user.example:
#        class: %guepe_user.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
